# ===============================
# MongoDB (MongoDB Atlas URI)
# ===============================
spring.data.mongodb.uri=mongodb+srv://traincape:parichay@traincapetechnology.1p6rbwq.mongodb.net/E-commerce?retryWrites=true&w=majority&appName=TraincapeTechnology


# ===============================
# JWT Secret
# ===============================
jwt.secret=YourSuperSecretJWTKey12345678901234567890



# ===============================
# Swagger/OpenAPI Configuration
# ===============================
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

# Optional: Server Port
# server.port=8080
